.TH BANG 6 "2015/05/18" "Games"
.SH NAME
bang - A card game with LAN multiplayer and AI implemented in C++
.SH SYNOPSIS
.B bang
[-h \fIhost\fR]
[-p \fIport\fR]
.I filename

.B bang
--help
.SH DESCRIPTION
Bang! is a Wild West-themed card game, designed by Emiliano Sciarra and released by Italian publisher daVinci Editrice in 2002.

This C++ implementation is inspired by the original game rules, but it is a little bit simplified.

The architecture is based on a client-server model. When a user hosts a game, GameServer is started as a separate process on his computer. Then all the users (even the host himself) are connecting with GameClient to that server via TCP stream sockets. Each client keeps 2 opened connections – one for synchronous two-way communication (API) and the other one for game state change events from the server. The port on which server is running must be accessible by other players' computers.
.SH OPTIONS
.TP 12
.B --help
Displays help end exits
.TP
.B -h \fIhost\R

Specifies game server IP address
.TP
.B -p \fIport\R

Specifies game server port number (default port is 7777)
.SH EXAMPLES
.TP 4
.B bang res/cards.csv
Runs the game with cards definitions in res/cards.csv file
.TP
.B bang -h 109.75.149.40 -p 1234 res/cards.csv
Runs the game with cards definitions in res/cards.csv file and server on 109.75.149.40:1234
.TP
.B bang --help
Displays help and exits
.SH "SEE ALSO"
For further developer documentation, generate HTML documentation by running
.I make doc
from the project directory.
.SH AUTHOR
Matous Skala <skalamat@fit.cvut.cz>
.SH COPYRIGHT
This project is available under the terms of the MIT License.
See LICENSE file for more information.
